[build]
  command = "npm install && npm run start"
  publish = "docs"

[functions]
directory = "api"
#external_node_modules = ["express"]
#node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[template.environment]
  ABLY_API_KEY = "mCWdHA.ttJ1BA:Gm7qL08ea0E8XFuY4CkAwxJZGaI2JuHKR56azpB3SGU"
